import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-subtle": "var(--bg-subtle)",
        surface: "var(--surface)",
        "surface-hover": "var(--surface-hover)",
        card: "var(--card)",
        border: "var(--border)",
        "border-subtle": "var(--border-subtle)",
        "border-accent": "var(--border-accent)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-subtle": "var(--accent-subtle)",
        success: "var(--success)",
      },
      fontFamily: {
        sans: [
          "var(--font-inter)",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        serif: ["Georgia", "Cambria", '"Times New Roman"', "Times", "serif"],
        mono: [
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      fontSize: {
        display: "var(--text-display)",
        h1: "var(--text-h1)",
        h2: "var(--text-h2)",
        h3: "var(--text-h3)",
        "body-lg": "var(--text-body-lg)",
        body: "var(--text-body)",
        small: "var(--text-small)",
        micro: "var(--text-micro)",
      },
      fontWeight: {
        normal: "400",
        book: "450",
        medium: "500",
        emphasis: "550",
        semibold: "600",
        hero: "620",
        bold: "700",
      },
      letterSpacing: {
        hero: "-0.025em",
        heading: "-0.02em",
        subheading: "-0.012em",
        tight: "-0.01em",
        normal: "0em",
        label: "0.01em",
        eyebrow: "0.035em",
      },
      lineHeight: {
        tight: "1.09",
        snug: "1.25",
        normal: "1.5",
        relaxed: "1.62",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "6px",
        md: "8px",
        lg: "10px",
        xl: "12px",
        "2xl": "16px",
      },
    },
  },
  plugins: [],
};
export default config;
